const res = document.getElementById("res")
const resDiv = document.getElementById("resDiv")
const input = document.getElementById("input")



function print() {

    res.style.color = "#03e8f400"

    setTimeout(()=> {
        res.style.color = "#03e9f4"

        if (input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaissãoassuashabilidades" || input.value.toLowerCase().trim().replace(/ /g,'') == "qualéasuahabilidade"|| input.value.toLowerCase().trim().replace(/ /g,'') == "quaissaoassuashabilidades") {
            res.innerHTML = "Minhas habilidedes são responder suas perguntas sobre meu criador, o Vinicius"
        }else if (input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemévocê" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemévoce" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemevoce" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "qualéoseunome" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "qualeoseunome" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemévice"  || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemévice"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemévoçê"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "queméviçe"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemévoçe"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemevoçe"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemevoçê") {
            res.innerHTML = "Meu nome é Aline, eu sou uma Inteligencia Artificial desenvolvida para responder suas perguntas sobre meu criador, Vinicius."
        }else if (input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalesobreele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalemaisdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalemaissobreele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalemasdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalemassobreele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "falesobreele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefaladele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "falemaisdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefaledele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefaladele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalasobreele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalamaissobreele" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalamaissobreele" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "queméovinicius" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemeovinicius"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemevinicius"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemévinicius"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "queméovini"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemeovini"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemévini"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quemeovini") {
            res.innerHTML = "Seu nome completo é Vinicius de Oliveira Gonçalves, sua data de nascimento 30/01/2001, um amante da computação, desde criança familiarizado com as máquinas, e desde o ano passado mergulhando neste mundo da programação"
        }else if (input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "ashabilidadesdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaissãoashabilidadesdoviniciusnaprogramação"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "qualéahabilidadedelenaprogramação"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "oqueelesabesobreprogramação"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalemassobreele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "falesobreele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "qualéahabilidadedelenaprogramação"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaissãoashabilidadesdelenaprogramação"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalesobreashabilidadesdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefaleashabilidadesdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "qualéahabilidadedele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaissãoashabilidadesdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaissaoashabilidadesdelenaprogramaçao"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaissãoashabilidadesdelenaprogramaçao"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaissaoashabilidadesdelenaprogramação") {
            res.innerHTML = "Ele estuda para ser um grande programador FullStack, tem um bom conhecimento sobre Python, JS, CSS, HTML, e também Django, NodeJS. Banco de dados estuda bastante o mongoDB e iniciando estudos sobre Mysql"
        }else if (input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "redesociais"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "suasredessociaiss"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "seugithub"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "seulinkedin"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "ogithubdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "asredessociaisdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaissãoasredessociaisdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "qualéaredesocialdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "qualolinkedindele") {
            res.innerHTML = "<a href='https://www.linkedin.com/in/vinicius-oliveira-904291248/' target='_blank' id='resLink'>CLique aqui para o Linkedin</a> <br> <br> <a href='https://github.com/ViniciusOliver99' target='_blank' id='resLink'>Clique aqui para o GitHub</a>"
        }else if (input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "osprojetosdele" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaissãoosprojetosdele" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "qualéoprojetodele" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaaleoprojetodele" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "seusprojetos" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "memostreosprojetosdele"  || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "memostreumprojetodele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "memostraumprojetoseu"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefaledosprojetosdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "projeto"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "projetos"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "umprojetodele" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalesobreosprojetosmostradonoinicio" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalesobreosprojetosdoinicio"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalesobreosprojetosdoiniciodoporti"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "mefalsobreosprojetosdoiníciodoportifólio") {
            res.innerHTML = "Os projetos dele foram mostrado no começo e os outros está em seu GitHub"
        }else if (input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "eleébom" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "eleebom" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "elesabemesmo" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "ebomele" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "elesabemesmo" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "eleéumbomfuncionário"  || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "elevaiserbom"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "elevaiserbom"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "elevaiserbom"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "projeto"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "eleebom"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "sabemesmo" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "devocontratarelemesmo") {
            res.innerHTML = "Sim, ele é bom, confia 😉"
        }else if (input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "suasexpeciênciasproficinais" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "suasexpecienciasproficinais" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "experiencia" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "experiência" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "experiencias" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "asexperiênciaprofissionaisdele"  || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "asexperienciaprofissionaisdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaisasexperiênciaprofissionaisdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "qualasexperienciaprofissionaisdele"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "experiêcias"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "profissional"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "profissionais" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "aondejátrabalhou" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "aondejatrabalhou" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "aondejátrabalhoucomoprogramador" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "aondejatrabalhoucomoprogramador") {
            res.innerHTML = "Ele nunca trabalhou como programador, já trabalhou em outros lugares, e trabalha atualmente mais nada relacionado a programação"
        }else if (input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "línguas" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "linguas" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "idiomas" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaisidiomaselesabefalar" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaislínguaselesabefalar" || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quaalidiomaelesabefalar"  || input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "qualidiomavocesabefalar"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "quallinguaelesabefalar"|| input.value.toLowerCase().trim().replace(/ /g,'').replace(/\?/g, '') == "seusidiomas") {
            res.innerHTML = "Sobre idiomas, ele está estudando, com muita dedicação o ingles, e prentende fica fluente em cerca de um ano, no momento ele consegue entender algumas palavras 'soltas' em ingles e nas leituras"
        }else {
            res.innerHTML = "Me desculpa, mas acho que você escreveu algo errado. <br>Tente novamente <br> Dicas: 'Quais são as habilidades dele', 'Quem é voçê', 'Quais as experiêcias profissionais dele', etc. "
        }

    },0500)

}